### ISSUE TITLE
Missing model weights

### ISSUE THREAD

**Issue by mongoose54** [plkmo/AlphaZero_Connect4#1]
Thank you for the wonderful work. I am trying to run the code but the initial weights of the network are missing:

`FileNotFoundError: [Errno 2] No such file or directory: './model_data/c4_current_net_trained2_iter0.pth.tar'
`

Could you share the weights file?

**Comment by plkmo** [comment]
Hi there,
Thanks for your interest. Sure, I have uploaded the model weights for the past iterations. If you would like to train the net from scratch and do some hyperparameter-tuning etc, you will have to comment out the torch.load portions in the code sorry about that

**Comment by fernandotenorio** [comment]
Hello!
I have one question, why are you not flipping the sign of "value" variable in MCTS_c4.py, after a terminal node is reached? For example, if player 1 won, shouldn't the rewards be [1, -1, 1, -1, ..., -1, 1] instead of [1, 1, 1, 1, ..., 1, 1]? 
Thanks!

**Comment by plkmo** [comment]
Hi, yes you're right about flipping values, the backup method in line 114 does flip the values
