### ISSUE TITLE
Incorrect scalar weight type in conv2d_forward call

### ISSUE THREAD

**Issue by m129chang** [plkmo/AlphaZero_Connect4#3]
First, thank you for writing your article and sharing the code on GitHub.  It provides a great starting point for someone interested in reinforcement learning.

I have encountered the problem mentioned in the issue title, but let me first describe my development environment:  a basic Windows 10 (i7-4790, 16GB) without CUDA support, JetBrains PyCharm IDE, and Python 3.7.  In order to compile the code under PyCharm, I needed to prefix some of the imports for your files  with "src." since they are loaded as part of the same project.  Also used PyCharm's built-in import optimizer to re-order the imports but don't think that broke anything.

Removed the .cuda() call in MCTS_c4.DummyNode.UCT_search() to fix an immediate execution error.

After 19 hours (and 120 games for each of 5 processors) the first iteration finished and the Neural Network began to train  Here is a trace log excerpt:

12/28/2019 06:49:38 AM [INFO]: Finished multi-process MCTS!
12/28/2019 06:49:38 AM [INFO]: Loading training data...
12/28/2019 06:49:39 AM [INFO]: Loaded data from ./datasets/iter_0/.
12/28/2019 06:49:39 AM [INFO]: Loaded checkpoint model ./model_data/cc4_current_net__iter0.pth.tar.
12/28/2019 06:49:39 AM [INFO]: Starting training process...
Update step size: 32
Traceback (most recent call last):
  File "C:/InstallationKits/AlphaZero_Connect4-master/src/main_pipeline.py", line 37, in <module>
    train_connectnet(args, iteration=i, new_optim_state=True)
  File "C:\InstallationKits\AlphaZero_Connect4-master\src\train_c4.py", line 155, in train_connectnet
    train(net, datasets, optimizer, scheduler, start_epoch, 0, args, iteration)
  File "C:\InstallationKits\AlphaZero_Connect4-master\src\train_c4.py", line 84, in train
    policy_pred, value_pred = net(state) # policy_pred = torch.Size([batch, 4672]) value_pred = torch.Size([batch, 1])
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\InstallationKits\AlphaZero_Connect4-master\src\alpha_net_c4.py", line 95, in forward
    s = self.conv(s)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\InstallationKits\AlphaZero_Connect4-master\src\alpha_net_c4.py", line 35, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'weight' in call to _thnn_conv2d_forward

Process finished with exit code 1

-----------------------------------------------------------------------------

Thank you in advance for any help you can give us.

**Comment by plkmo** [comment]
Thanks and glad that you've find it useful. I have yet to test it fully on non-cuda environments yet but your issue is with line 79-80 train_c4.train function. 
After

if cuda:
     state, policy, value = state.cuda().float(), policy.float().cuda(), value.cuda().float()

add the following lines and you should be fine:

else:
     state, policy, value = state.float(), policy.float(), value.float()

Its an error and I will update it soon.

**Comment by m129chang** [comment]
Thank you very much for your quick response and immediate fix.  I have been
working my way through the code but since I am mainly a Java and C
programmer I didn't understand what was missing in terms of
initialization.

By sharing your hard work and code, you have done a tremendous service to
those of us who wish to learn more about reinforcement learning but lack
the background in Python and the supporting packages like PyTorch,
Tensorflow, etc.  Thank you again for your generosity.

Have a Happy New Year.

Michael Chang

**Comment by plkmo** [comment]
No problem, its an open-source community. Do let me know of your training progress, though I wouldn't really recommend running using non-cuda environment as the process can take really long since you would need more than thousands of games before it shows some learning. It took me a few weeks running on a 4 GB gpu..

Happy New Year to you too
